image:
  repository: quasarcelestio/task-1.0
  tag: 894d8fbfca6892336b9398c3af76489309ebd209
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort
  port: 9000
  targetPort: 9000
  nodePort: 30001